schemaVersion: '2.0.0'
commandTests:
  - name: "git"
    command: "git"
    args: ["--version"]
    expectedOutput: ["^git version 2\\.[0-9]+\\.[0-9]+\\n$"]

  - name: "pre-commit"
    command: "pre-commit"
    args: ["-V"]
    expectedOutput: ["^pre-commit ([0-9]+\\.){2}[0-9]+\\n$"]

  - name: "terraform"
    command: "terraform"
    args: ["-version"]
    expectedOutput: ["^Terraform v([0-9]+\\.){2}[0-9]+\\non linux_amd64\\n$"]

  - name: "checkov"
    command: "checkov"
    args: ["--version"]
    expectedOutput: ["^([0-9]+\\.){2}[0-9]+\\n$"]

  - name: "infracost"
    command: "infracost"
    args: ["--version"]
    expectedOutput: ["^Infracost v([0-9]+\\.){2}[0-9]+\\n$"]

  - name: "terraform-docs"
    command: "terraform-docs"
    args: ["--version"]
    expectedOutput: ["^terraform-docs version v([0-9]+\\.){2}[0-9]+ [a-z0-9]+ linux/amd64\\n$"]

  - name: "terragrunt"
    command: "terragrunt"
    args: ["--version"]
    expectedOutput: ["^terragrunt version v([0-9]+\\.){2}[0-9]+\\n$"]

  - name: "terrascan"
    command: "terrascan"
    args: [ "version" ]
    expectedOutput: [ "^version: v([0-9]+\\.){2}[0-9]+\\n$" ]

  - name: "tflint"
    command: "tflint"
    args: [ "--version" ]
    expectedOutput: [ "TFLint version ([0-9]+\\.){2}[0-9]+\\n$" ]

  - name: "tfsec"
    command: "tfsec"
    args: [ "--version" ]
    expectedOutput: [ "([0-9]+\\.){2}[0-9]+\\n$" ]

  - name: "tfupdate"
    command: "tfupdate"
    args: [ "--version" ]
    expectedOutput: [ "([0-9]+\\.){2}[0-9]+\\n$" ]

  - name: "hcledit"
    command: "hcledit"
    args: [ "version" ]
    expectedOutput: [ "([0-9]+\\.){2}[0-9]+\\n$" ]

fileExistenceTests:
  - name: 'terrascan init'
    path: '/root/.terrascan/pkg/policies/opa/rego/github/github_repository/privateRepoEnabled.rego'
    shouldExist: true
    uid: 0
    gid: 0
