# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
reviews:
  collapse_walkthrough: true
  related_issues: false
  related_prs: false
  high_level_summary_in_walkthrough: true
  poem: false
  auto_review:
    drafts: true
