---

codecov:
  notify:
    after_n_builds: 21  # Number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: >-  # notsecret  # repo-scoped, upload-only, stability in fork PRs
    REPLACE WITH A CLEAR-TEXT TOKEN

comment:
  require_changes: true

coverage:
  range: 100..100
  status:
    patch:
      default:
        target: 100%
      pytest:
        target: 50%
        flags:
        - pytest
      typing:
        flags:
        - MyPy
    project:
      default:
        target: 100%
      lib:
        flags:
        - pytest
        paths:
        - src/
        target: 100%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 100%
      typing:
        flags:
        - MyPy
        target: 100%

...
