-   id: terraform_fmt
    name: Terraform fmt
    description: Rewrites all Terraform configuration files to a canonical format.
    entry: terraform_fmt.sh
    language: script
    files: \.tf$
    exclude: \.+.terraform\/.*$
