- id: terraform_fmt
  name: Terraform fmt
  description: Rewrites all Terraform configuration files to a canonical format.
  entry: terraform_fmt.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform_docs
  name: Terraform docs
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: terraform_docs.sh
  args: [--args=--with-aggregate-type-defaults]
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform_docs_without_aggregate_type_defaults
  name: Terraform docs (without aggregate type defaults)
  description: Inserts input and output documentation into README.md (using terraform-docs).
  require_serial: true
  entry: terraform_docs.sh
  language: script
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform_docs_replace
  name: Terraform docs (overwrite README.md)
  description: Overwrite content of README.md with terraform-docs.
  require_serial: true
  entry: terraform_docs_replace
  language: python
  files: (\.tf)$
  exclude: \.terraform\/.*$

- id: terraform_validate
  name: Terraform validate without variables
  description: Validates all Terraform configuration files.
  entry: terraform_validate.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terraform_tflint
  name: Terraform validate with tflint
  description: Validates all Terraform configuration files with TFLint.
  entry: terraform_tflint.sh
  language: script
  files: (\.tf|\.tfvars)$
  exclude: \.terraform\/.*$

- id: terragrunt_fmt
  name: Terragrunt fmt
  description: Rewrites all Terragrunt configuration files to a canonical format.
  entry: terragrunt_fmt.sh
  language: script
  files: (\.hcl)$
  exclude: \.terraform\/.*$
