[build.targets.sdist]
include = [
  'hooks/*.py',
]
exclude = [
  'hooks/*.sh',
]

[build.targets.wheel]
packages = [
  'hooks/',
]

[metadata.hooks.vcs.urls]
'Source Archive' = 'https://github.com/antonbabenko/pre-commit-terraform/archive/{commit_hash}.tar.gz'
'GitHub: repo' = 'https://github.com/antonbabenko/pre-commit-terraform'

[version]
source = 'vcs'
